version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      # Lambda 1
      - sam build --template-file template.yaml --build-dir .aws-sam/build
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${S3BucketName} --output-template-file out-imagecropper-lambda.yaml
      -
artifacts:
  files:
    - out-imagecropper-lambda.yaml